version: '2'
services:
  nagios:
    image: ethnchao/nagios
    container_name: nagios
    command: --enable-ndo --create-db --server-url http://192.168.101.100:4000
    ports:
      - 4000:80
      - 4001:3000
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - nagios_mysql
    volumes:
      - ./data/plugin:/data/plugin
      - ./data/conf:/usr/local/nagios/etc/mount
      - ./data/example:/data/example

  nagios_mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - MYSQL_USER=nagios
      - MYSQL_PASSWORD=nagios
      - MYSQL_ADDRESS=nagios_mysql
      - MYSQL_DATABASE=nagios
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - nagios_db_data:/var/lib/mysql

volumes:
  nagios_db_data:
